version: '3.7'

networks:
  library_api:

services:
  app:
    build:
      context: ./docker/php-fpm
      dockerfile: App.DockerFile
    container_name: library_api_app
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
    volumes:
      - "./:/var/www/library_api"
    networks:
      - library_api
  web:
    image: nginx:1.19.0
    container_name: library_api_web
    volumes:
      - "./:/var/www/library_api"
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./docker/nginx/php-fpm.conf:/etc/nginx/conf.d/php-fpm.conf"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:80"
    networks:
      - library_api
  db:
    image: mysql:8
    container_name: library_api_db
    environment:
      MYSQL_ROOT_PASSWORD: library_api2020!
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql:/var/lib/mysql"
    networks:
      - library_api